# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cgx_driver/RobotGetAllDAOutputRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RobotGetAllDAOutputRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "cgx_driver/RobotGetAllDAOutputRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# RobotGetAllDAOutput.srv
"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotGetAllDAOutputRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cgx_driver/RobotGetAllDAOutputResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RobotGetAllDAOutputResponse(genpy.Message):
  _md5sum = "fdb3ecd52fd607089bccc8ca9c27eda0"
  _type = "cgx_driver/RobotGetAllDAOutputResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool[8] controllerDO
bool[8] controllerCO
float32[1] controllerAO
bool[2] toolDO
int16 ret
string message
"""
  __slots__ = ['controllerDO','controllerCO','controllerAO','toolDO','ret','message']
  _slot_types = ['bool[8]','bool[8]','float32[1]','bool[2]','int16','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       controllerDO,controllerCO,controllerAO,toolDO,ret,message

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotGetAllDAOutputResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.controllerDO is None:
        self.controllerDO = [False] * 8
      if self.controllerCO is None:
        self.controllerCO = [False] * 8
      if self.controllerAO is None:
        self.controllerAO = [0.] * 1
      if self.toolDO is None:
        self.toolDO = [False] * 2
      if self.ret is None:
        self.ret = 0
      if self.message is None:
        self.message = ''
    else:
      self.controllerDO = [False] * 8
      self.controllerCO = [False] * 8
      self.controllerAO = [0.] * 1
      self.toolDO = [False] * 2
      self.ret = 0
      self.message = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_8B().pack(*self.controllerDO))
      buff.write(_get_struct_8B().pack(*self.controllerCO))
      buff.write(_get_struct_1f().pack(*self.controllerAO))
      buff.write(_get_struct_2B().pack(*self.toolDO))
      _x = self.ret
      buff.write(_get_struct_h().pack(_x))
      _x = self.message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      self.controllerDO = _get_struct_8B().unpack(str[start:end])
      self.controllerDO = list(map(bool, self.controllerDO))
      start = end
      end += 8
      self.controllerCO = _get_struct_8B().unpack(str[start:end])
      self.controllerCO = list(map(bool, self.controllerCO))
      start = end
      end += 4
      self.controllerAO = _get_struct_1f().unpack(str[start:end])
      start = end
      end += 2
      self.toolDO = _get_struct_2B().unpack(str[start:end])
      self.toolDO = list(map(bool, self.toolDO))
      start = end
      end += 2
      (self.ret,) = _get_struct_h().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.message = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.message = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.controllerDO.tostring())
      buff.write(self.controllerCO.tostring())
      buff.write(self.controllerAO.tostring())
      buff.write(self.toolDO.tostring())
      _x = self.ret
      buff.write(_get_struct_h().pack(_x))
      _x = self.message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      self.controllerDO = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=8)
      self.controllerDO = list(map(bool, self.controllerDO))
      start = end
      end += 8
      self.controllerCO = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=8)
      self.controllerCO = list(map(bool, self.controllerCO))
      start = end
      end += 4
      self.controllerAO = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=1)
      start = end
      end += 2
      self.toolDO = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=2)
      self.toolDO = list(map(bool, self.toolDO))
      start = end
      end += 2
      (self.ret,) = _get_struct_h().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.message = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.message = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_1f = None
def _get_struct_1f():
    global _struct_1f
    if _struct_1f is None:
        _struct_1f = struct.Struct("<1f")
    return _struct_1f
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
_struct_8B = None
def _get_struct_8B():
    global _struct_8B
    if _struct_8B is None:
        _struct_8B = struct.Struct("<8B")
    return _struct_8B
_struct_h = None
def _get_struct_h():
    global _struct_h
    if _struct_h is None:
        _struct_h = struct.Struct("<h")
    return _struct_h
class RobotGetAllDAOutput(object):
  _type          = 'cgx_driver/RobotGetAllDAOutput'
  _md5sum = 'fdb3ecd52fd607089bccc8ca9c27eda0'
  _request_class  = RobotGetAllDAOutputRequest
  _response_class = RobotGetAllDAOutputResponse
