# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cgx_driver/RobotGetAllDAInputRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RobotGetAllDAInputRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "cgx_driver/RobotGetAllDAInputRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# RobotGetAllDAInput.srv
"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotGetAllDAInputRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cgx_driver/RobotGetAllDAInputResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RobotGetAllDAInputResponse(genpy.Message):
  _md5sum = "cba808cbeaab4420830cd2c51b834403"
  _type = "cgx_driver/RobotGetAllDAInputResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool[8] controllerDI
bool[8] controllerCI
float32[3] controllerAI
bool[2] toolDI
float32[2] toolAI
int16 ret
string message
"""
  __slots__ = ['controllerDI','controllerCI','controllerAI','toolDI','toolAI','ret','message']
  _slot_types = ['bool[8]','bool[8]','float32[3]','bool[2]','float32[2]','int16','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       controllerDI,controllerCI,controllerAI,toolDI,toolAI,ret,message

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotGetAllDAInputResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.controllerDI is None:
        self.controllerDI = [False] * 8
      if self.controllerCI is None:
        self.controllerCI = [False] * 8
      if self.controllerAI is None:
        self.controllerAI = [0.] * 3
      if self.toolDI is None:
        self.toolDI = [False] * 2
      if self.toolAI is None:
        self.toolAI = [0.] * 2
      if self.ret is None:
        self.ret = 0
      if self.message is None:
        self.message = ''
    else:
      self.controllerDI = [False] * 8
      self.controllerCI = [False] * 8
      self.controllerAI = [0.] * 3
      self.toolDI = [False] * 2
      self.toolAI = [0.] * 2
      self.ret = 0
      self.message = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_8B().pack(*self.controllerDI))
      buff.write(_get_struct_8B().pack(*self.controllerCI))
      buff.write(_get_struct_3f().pack(*self.controllerAI))
      buff.write(_get_struct_2B().pack(*self.toolDI))
      buff.write(_get_struct_2f().pack(*self.toolAI))
      _x = self.ret
      buff.write(_get_struct_h().pack(_x))
      _x = self.message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      self.controllerDI = _get_struct_8B().unpack(str[start:end])
      self.controllerDI = list(map(bool, self.controllerDI))
      start = end
      end += 8
      self.controllerCI = _get_struct_8B().unpack(str[start:end])
      self.controllerCI = list(map(bool, self.controllerCI))
      start = end
      end += 12
      self.controllerAI = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 2
      self.toolDI = _get_struct_2B().unpack(str[start:end])
      self.toolDI = list(map(bool, self.toolDI))
      start = end
      end += 8
      self.toolAI = _get_struct_2f().unpack(str[start:end])
      start = end
      end += 2
      (self.ret,) = _get_struct_h().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.message = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.message = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.controllerDI.tostring())
      buff.write(self.controllerCI.tostring())
      buff.write(self.controllerAI.tostring())
      buff.write(self.toolDI.tostring())
      buff.write(self.toolAI.tostring())
      _x = self.ret
      buff.write(_get_struct_h().pack(_x))
      _x = self.message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      self.controllerDI = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=8)
      self.controllerDI = list(map(bool, self.controllerDI))
      start = end
      end += 8
      self.controllerCI = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=8)
      self.controllerCI = list(map(bool, self.controllerCI))
      start = end
      end += 12
      self.controllerAI = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 2
      self.toolDI = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=2)
      self.toolDI = list(map(bool, self.toolDI))
      start = end
      end += 8
      self.toolAI = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=2)
      start = end
      end += 2
      (self.ret,) = _get_struct_h().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.message = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.message = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_8B = None
def _get_struct_8B():
    global _struct_8B
    if _struct_8B is None:
        _struct_8B = struct.Struct("<8B")
    return _struct_8B
_struct_h = None
def _get_struct_h():
    global _struct_h
    if _struct_h is None:
        _struct_h = struct.Struct("<h")
    return _struct_h
class RobotGetAllDAInput(object):
  _type          = 'cgx_driver/RobotGetAllDAInput'
  _md5sum = 'cba808cbeaab4420830cd2c51b834403'
  _request_class  = RobotGetAllDAInputRequest
  _response_class = RobotGetAllDAInputResponse
