(cl:in-package cgx_driver-srv)
(cl:export '(MID_POSE-VAL
          MID_POSE
          MID_JOINTPOS-VAL
          MID_JOINTPOS
          MID_SPEED-VAL
          MID_SPEED
          MID_ACC-VAL
          MID_ACC
          MID_COORDINATE_TYPE-VAL
          MID_COORDINATE_TYPE
          MID_POINT_TRANS_TYPE-VAL
          MID_POINT_TRANS_TYPE
          END_POSE-VAL
          END_POSE
          END_JOINTPOS-VAL
          END_JOINTPOS
          END_SPEED-VAL
          END_SPEED
          END_ACC-VAL
          END_ACC
          END_COORDINATE_TYPE-VAL
          END_COORDINATE_TYPE
          END_POINT_TRANS_TYPE-VAL
          END_POINT_TRANS_TYPE
          END_IS_BLOCK-VAL
          END_IS_BLOCK
          RET-VAL
          RET
          MESSAGE-VAL
          MESSAGE
))