// Generated by gencpp from file cgx_driver/CgxDriverServiceResponse.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_CGXDRIVERSERVICERESPONSE_H
#define CGX_DRIVER_MESSAGE_CGXDRIVERSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cgx_driver
{
template <class ContainerAllocator>
struct CgxDriverServiceResponse_
{
  typedef CgxDriverServiceResponse_<ContainerAllocator> Type;

  CgxDriverServiceResponse_()
    : ret(0)
    , message()  {
    }
  CgxDriverServiceResponse_(const ContainerAllocator& _alloc)
    : ret(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _ret_type;
  _ret_type ret;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CgxDriverServiceResponse_

typedef ::cgx_driver::CgxDriverServiceResponse_<std::allocator<void> > CgxDriverServiceResponse;

typedef boost::shared_ptr< ::cgx_driver::CgxDriverServiceResponse > CgxDriverServiceResponsePtr;
typedef boost::shared_ptr< ::cgx_driver::CgxDriverServiceResponse const> CgxDriverServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator1> & lhs, const ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ret == rhs.ret &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator1> & lhs, const ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cgx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76c68a2c5e109f4d6a4dc1cfc355f405";
  }

  static const char* value(const ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76c68a2c5e109f4dULL;
  static const uint64_t static_value2 = 0x6a4dc1cfc355f405ULL;
};

template<class ContainerAllocator>
struct DataType< ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cgx_driver/CgxDriverServiceResponse";
  }

  static const char* value(const ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 ret\n"
"string message\n"
;
  }

  static const char* value(const ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CgxDriverServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cgx_driver::CgxDriverServiceResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "ret: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ret);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_CGXDRIVERSERVICERESPONSE_H
