// Generated by gencpp from file cgx_driver/CgxDriverServiceRequest.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_CGXDRIVERSERVICEREQUEST_H
#define CGX_DRIVER_MESSAGE_CGXDRIVERSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cgx_driver
{
template <class ContainerAllocator>
struct CgxDriverServiceRequest_
{
  typedef CgxDriverServiceRequest_<ContainerAllocator> Type;

  CgxDriverServiceRequest_()
    : pose()
    , jointpos()
    , speed()
    , acc()
    , coordinate_type()
    , point_trans_type()
    , point_trans_radius(0.0)
    , is_block(0)  {
    }
  CgxDriverServiceRequest_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , jointpos(_alloc)
    , speed(_alloc)
    , acc(_alloc)
    , coordinate_type(_alloc)
    , point_trans_type(_alloc)
    , point_trans_radius(0.0)
    , is_block(0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _pose_type;
  _pose_type pose;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _jointpos_type;
  _jointpos_type jointpos;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _speed_type;
  _speed_type speed;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _acc_type;
  _acc_type acc;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _coordinate_type_type;
  _coordinate_type_type coordinate_type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _point_trans_type_type;
  _point_trans_type_type point_trans_type;

   typedef float _point_trans_radius_type;
  _point_trans_radius_type point_trans_radius;

   typedef int16_t _is_block_type;
  _is_block_type is_block;





  typedef boost::shared_ptr< ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CgxDriverServiceRequest_

typedef ::cgx_driver::CgxDriverServiceRequest_<std::allocator<void> > CgxDriverServiceRequest;

typedef boost::shared_ptr< ::cgx_driver::CgxDriverServiceRequest > CgxDriverServiceRequestPtr;
typedef boost::shared_ptr< ::cgx_driver::CgxDriverServiceRequest const> CgxDriverServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator1> & lhs, const ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.jointpos == rhs.jointpos &&
    lhs.speed == rhs.speed &&
    lhs.acc == rhs.acc &&
    lhs.coordinate_type == rhs.coordinate_type &&
    lhs.point_trans_type == rhs.point_trans_type &&
    lhs.point_trans_radius == rhs.point_trans_radius &&
    lhs.is_block == rhs.is_block;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator1> & lhs, const ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cgx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9423d0e42729a481a879e239cf18b382";
  }

  static const char* value(const ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9423d0e42729a481ULL;
  static const uint64_t static_value2 = 0xa879e239cf18b382ULL;
};

template<class ContainerAllocator>
struct DataType< ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cgx_driver/CgxDriverServiceRequest";
  }

  static const char* value(const ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# CgxDriverServiceMove.srv\n"
"float32[] pose\n"
"float32[] jointpos\n"
"float32[] speed\n"
"float32[] acc\n"
"string coordinate_type\n"
"string point_trans_type\n"
"float32 point_trans_radius\n"
"int16 is_block\n"
;
  }

  static const char* value(const ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.jointpos);
      stream.next(m.speed);
      stream.next(m.acc);
      stream.next(m.coordinate_type);
      stream.next(m.point_trans_type);
      stream.next(m.point_trans_radius);
      stream.next(m.is_block);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CgxDriverServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cgx_driver::CgxDriverServiceRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    if (v.pose.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.pose[i]);
    }
    if (v.pose.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "jointpos: ";
    if (v.jointpos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.jointpos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.jointpos[i]);
    }
    if (v.jointpos.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "speed: ";
    if (v.speed.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.speed.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.speed[i]);
    }
    if (v.speed.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc: ";
    if (v.acc.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.acc.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.acc[i]);
    }
    if (v.acc.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "coordinate_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.coordinate_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "point_trans_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.point_trans_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "point_trans_radius: ";
    Printer<float>::stream(s, indent + "  ", v.point_trans_radius);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_block: ";
    Printer<int16_t>::stream(s, indent + "  ", v.is_block);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_CGXDRIVERSERVICEREQUEST_H
