// Generated by gencpp from file cgx_driver/CgxDriverService.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_CGXDRIVERSERVICE_H
#define CGX_DRIVER_MESSAGE_CGXDRIVERSERVICE_H

#include <ros/service_traits.h>


#include <cgx_driver/CgxDriverServiceRequest.h>
#include <cgx_driver/CgxDriverServiceResponse.h>


namespace cgx_driver
{

struct CgxDriverService
{

typedef CgxDriverServiceRequest Request;
typedef CgxDriverServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CgxDriverService
} // namespace cgx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cgx_driver::CgxDriverService > {
  static const char* value()
  {
    return "f09746e49ae11d9f53a9e2220e8db09a";
  }

  static const char* value(const ::cgx_driver::CgxDriverService&) { return value(); }
};

template<>
struct DataType< ::cgx_driver::CgxDriverService > {
  static const char* value()
  {
    return "cgx_driver/CgxDriverService";
  }

  static const char* value(const ::cgx_driver::CgxDriverService&) { return value(); }
};


// service_traits::MD5Sum< ::cgx_driver::CgxDriverServiceRequest> should match
// service_traits::MD5Sum< ::cgx_driver::CgxDriverService >
template<>
struct MD5Sum< ::cgx_driver::CgxDriverServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::CgxDriverService >::value();
  }
  static const char* value(const ::cgx_driver::CgxDriverServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::CgxDriverServiceRequest> should match
// service_traits::DataType< ::cgx_driver::CgxDriverService >
template<>
struct DataType< ::cgx_driver::CgxDriverServiceRequest>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::CgxDriverService >::value();
  }
  static const char* value(const ::cgx_driver::CgxDriverServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cgx_driver::CgxDriverServiceResponse> should match
// service_traits::MD5Sum< ::cgx_driver::CgxDriverService >
template<>
struct MD5Sum< ::cgx_driver::CgxDriverServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::CgxDriverService >::value();
  }
  static const char* value(const ::cgx_driver::CgxDriverServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::CgxDriverServiceResponse> should match
// service_traits::DataType< ::cgx_driver::CgxDriverService >
template<>
struct DataType< ::cgx_driver::CgxDriverServiceResponse>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::CgxDriverService >::value();
  }
  static const char* value(const ::cgx_driver::CgxDriverServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_CGXDRIVERSERVICE_H
