// Generated by gencpp from file cgx_driver/RobotControl.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTCONTROL_H
#define CGX_DRIVER_MESSAGE_ROBOTCONTROL_H

#include <ros/service_traits.h>


#include <cgx_driver/RobotControlRequest.h>
#include <cgx_driver/RobotControlResponse.h>


namespace cgx_driver
{

struct RobotControl
{

typedef RobotControlRequest Request;
typedef RobotControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotControl
} // namespace cgx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cgx_driver::RobotControl > {
  static const char* value()
  {
    return "afdb845140e2f05f77c770110f12be2b";
  }

  static const char* value(const ::cgx_driver::RobotControl&) { return value(); }
};

template<>
struct DataType< ::cgx_driver::RobotControl > {
  static const char* value()
  {
    return "cgx_driver/RobotControl";
  }

  static const char* value(const ::cgx_driver::RobotControl&) { return value(); }
};


// service_traits::MD5Sum< ::cgx_driver::RobotControlRequest> should match
// service_traits::MD5Sum< ::cgx_driver::RobotControl >
template<>
struct MD5Sum< ::cgx_driver::RobotControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotControl >::value();
  }
  static const char* value(const ::cgx_driver::RobotControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotControlRequest> should match
// service_traits::DataType< ::cgx_driver::RobotControl >
template<>
struct DataType< ::cgx_driver::RobotControlRequest>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotControl >::value();
  }
  static const char* value(const ::cgx_driver::RobotControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cgx_driver::RobotControlResponse> should match
// service_traits::MD5Sum< ::cgx_driver::RobotControl >
template<>
struct MD5Sum< ::cgx_driver::RobotControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotControl >::value();
  }
  static const char* value(const ::cgx_driver::RobotControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotControlResponse> should match
// service_traits::DataType< ::cgx_driver::RobotControl >
template<>
struct DataType< ::cgx_driver::RobotControlResponse>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotControl >::value();
  }
  static const char* value(const ::cgx_driver::RobotControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTCONTROL_H
