// Generated by gencpp from file cgx_driver/RobotGetAllDAInput.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTGETALLDAINPUT_H
#define CGX_DRIVER_MESSAGE_ROBOTGETALLDAINPUT_H

#include <ros/service_traits.h>


#include <cgx_driver/RobotGetAllDAInputRequest.h>
#include <cgx_driver/RobotGetAllDAInputResponse.h>


namespace cgx_driver
{

struct RobotGetAllDAInput
{

typedef RobotGetAllDAInputRequest Request;
typedef RobotGetAllDAInputResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotGetAllDAInput
} // namespace cgx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cgx_driver::RobotGetAllDAInput > {
  static const char* value()
  {
    return "cba808cbeaab4420830cd2c51b834403";
  }

  static const char* value(const ::cgx_driver::RobotGetAllDAInput&) { return value(); }
};

template<>
struct DataType< ::cgx_driver::RobotGetAllDAInput > {
  static const char* value()
  {
    return "cgx_driver/RobotGetAllDAInput";
  }

  static const char* value(const ::cgx_driver::RobotGetAllDAInput&) { return value(); }
};


// service_traits::MD5Sum< ::cgx_driver::RobotGetAllDAInputRequest> should match
// service_traits::MD5Sum< ::cgx_driver::RobotGetAllDAInput >
template<>
struct MD5Sum< ::cgx_driver::RobotGetAllDAInputRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotGetAllDAInput >::value();
  }
  static const char* value(const ::cgx_driver::RobotGetAllDAInputRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotGetAllDAInputRequest> should match
// service_traits::DataType< ::cgx_driver::RobotGetAllDAInput >
template<>
struct DataType< ::cgx_driver::RobotGetAllDAInputRequest>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotGetAllDAInput >::value();
  }
  static const char* value(const ::cgx_driver::RobotGetAllDAInputRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cgx_driver::RobotGetAllDAInputResponse> should match
// service_traits::MD5Sum< ::cgx_driver::RobotGetAllDAInput >
template<>
struct MD5Sum< ::cgx_driver::RobotGetAllDAInputResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotGetAllDAInput >::value();
  }
  static const char* value(const ::cgx_driver::RobotGetAllDAInputResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotGetAllDAInputResponse> should match
// service_traits::DataType< ::cgx_driver::RobotGetAllDAInput >
template<>
struct DataType< ::cgx_driver::RobotGetAllDAInputResponse>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotGetAllDAInput >::value();
  }
  static const char* value(const ::cgx_driver::RobotGetAllDAInputResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTGETALLDAINPUT_H
