// Generated by gencpp from file cgx_driver/RobotGetAnalogIOState.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTGETANALOGIOSTATE_H
#define CGX_DRIVER_MESSAGE_ROBOTGETANALOGIOSTATE_H

#include <ros/service_traits.h>


#include <cgx_driver/RobotGetAnalogIOStateRequest.h>
#include <cgx_driver/RobotGetAnalogIOStateResponse.h>


namespace cgx_driver
{

struct RobotGetAnalogIOState
{

typedef RobotGetAnalogIOStateRequest Request;
typedef RobotGetAnalogIOStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotGetAnalogIOState
} // namespace cgx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cgx_driver::RobotGetAnalogIOState > {
  static const char* value()
  {
    return "8eeb73d9e3399a3bcd072ace63e97558";
  }

  static const char* value(const ::cgx_driver::RobotGetAnalogIOState&) { return value(); }
};

template<>
struct DataType< ::cgx_driver::RobotGetAnalogIOState > {
  static const char* value()
  {
    return "cgx_driver/RobotGetAnalogIOState";
  }

  static const char* value(const ::cgx_driver::RobotGetAnalogIOState&) { return value(); }
};


// service_traits::MD5Sum< ::cgx_driver::RobotGetAnalogIOStateRequest> should match
// service_traits::MD5Sum< ::cgx_driver::RobotGetAnalogIOState >
template<>
struct MD5Sum< ::cgx_driver::RobotGetAnalogIOStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotGetAnalogIOState >::value();
  }
  static const char* value(const ::cgx_driver::RobotGetAnalogIOStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotGetAnalogIOStateRequest> should match
// service_traits::DataType< ::cgx_driver::RobotGetAnalogIOState >
template<>
struct DataType< ::cgx_driver::RobotGetAnalogIOStateRequest>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotGetAnalogIOState >::value();
  }
  static const char* value(const ::cgx_driver::RobotGetAnalogIOStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cgx_driver::RobotGetAnalogIOStateResponse> should match
// service_traits::MD5Sum< ::cgx_driver::RobotGetAnalogIOState >
template<>
struct MD5Sum< ::cgx_driver::RobotGetAnalogIOStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotGetAnalogIOState >::value();
  }
  static const char* value(const ::cgx_driver::RobotGetAnalogIOStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotGetAnalogIOStateResponse> should match
// service_traits::DataType< ::cgx_driver::RobotGetAnalogIOState >
template<>
struct DataType< ::cgx_driver::RobotGetAnalogIOStateResponse>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotGetAnalogIOState >::value();
  }
  static const char* value(const ::cgx_driver::RobotGetAnalogIOStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTGETANALOGIOSTATE_H
