// Generated by gencpp from file cgx_driver/RobotStateCurrentResponse.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTSTATECURRENTRESPONSE_H
#define CGX_DRIVER_MESSAGE_ROBOTSTATECURRENTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cgx_driver
{
template <class ContainerAllocator>
struct RobotStateCurrentResponse_
{
  typedef RobotStateCurrentResponse_<ContainerAllocator> Type;

  RobotStateCurrentResponse_()
    : current()
    , ret(0)
    , message()  {
      current.assign(0.0);
  }
  RobotStateCurrentResponse_(const ContainerAllocator& _alloc)
    : current()
    , ret(0)
    , message(_alloc)  {
  (void)_alloc;
      current.assign(0.0);
  }



   typedef boost::array<double, 6>  _current_type;
  _current_type current;

   typedef int32_t _ret_type;
  _ret_type ret;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStateCurrentResponse_

typedef ::cgx_driver::RobotStateCurrentResponse_<std::allocator<void> > RobotStateCurrentResponse;

typedef boost::shared_ptr< ::cgx_driver::RobotStateCurrentResponse > RobotStateCurrentResponsePtr;
typedef boost::shared_ptr< ::cgx_driver::RobotStateCurrentResponse const> RobotStateCurrentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator2> & rhs)
{
  return lhs.current == rhs.current &&
    lhs.ret == rhs.ret &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cgx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "72a586880c39d961d06c55803979df7b";
  }

  static const char* value(const ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x72a586880c39d961ULL;
  static const uint64_t static_value2 = 0xd06c55803979df7bULL;
};

template<class ContainerAllocator>
struct DataType< ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cgx_driver/RobotStateCurrentResponse";
  }

  static const char* value(const ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[6] current  \n"
"int32 ret        # 返回状态码\n"
"string message   # 返回信息\n"
;
  }

  static const char* value(const ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current);
      stream.next(m.ret);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStateCurrentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cgx_driver::RobotStateCurrentResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "current: ";
    if (v.current.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.current.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.current[i]);
    }
    if (v.current.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ret: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ret);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTSTATECURRENTRESPONSE_H
