// Generated by gencpp from file cgx_driver/RobotGetDigitalIOState.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTGETDIGITALIOSTATE_H
#define CGX_DRIVER_MESSAGE_ROBOTGETDIGITALIOSTATE_H

#include <ros/service_traits.h>


#include <cgx_driver/RobotGetDigitalIOStateRequest.h>
#include <cgx_driver/RobotGetDigitalIOStateResponse.h>


namespace cgx_driver
{

struct RobotGetDigitalIOState
{

typedef RobotGetDigitalIOStateRequest Request;
typedef RobotGetDigitalIOStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotGetDigitalIOState
} // namespace cgx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cgx_driver::RobotGetDigitalIOState > {
  static const char* value()
  {
    return "5e121ca88187de900c90789129201008";
  }

  static const char* value(const ::cgx_driver::RobotGetDigitalIOState&) { return value(); }
};

template<>
struct DataType< ::cgx_driver::RobotGetDigitalIOState > {
  static const char* value()
  {
    return "cgx_driver/RobotGetDigitalIOState";
  }

  static const char* value(const ::cgx_driver::RobotGetDigitalIOState&) { return value(); }
};


// service_traits::MD5Sum< ::cgx_driver::RobotGetDigitalIOStateRequest> should match
// service_traits::MD5Sum< ::cgx_driver::RobotGetDigitalIOState >
template<>
struct MD5Sum< ::cgx_driver::RobotGetDigitalIOStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotGetDigitalIOState >::value();
  }
  static const char* value(const ::cgx_driver::RobotGetDigitalIOStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotGetDigitalIOStateRequest> should match
// service_traits::DataType< ::cgx_driver::RobotGetDigitalIOState >
template<>
struct DataType< ::cgx_driver::RobotGetDigitalIOStateRequest>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotGetDigitalIOState >::value();
  }
  static const char* value(const ::cgx_driver::RobotGetDigitalIOStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cgx_driver::RobotGetDigitalIOStateResponse> should match
// service_traits::MD5Sum< ::cgx_driver::RobotGetDigitalIOState >
template<>
struct MD5Sum< ::cgx_driver::RobotGetDigitalIOStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotGetDigitalIOState >::value();
  }
  static const char* value(const ::cgx_driver::RobotGetDigitalIOStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotGetDigitalIOStateResponse> should match
// service_traits::DataType< ::cgx_driver::RobotGetDigitalIOState >
template<>
struct DataType< ::cgx_driver::RobotGetDigitalIOStateResponse>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotGetDigitalIOState >::value();
  }
  static const char* value(const ::cgx_driver::RobotGetDigitalIOStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTGETDIGITALIOSTATE_H
