// Generated by gencpp from file cgx_driver/RobotGetAllDAOutputResponse.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTGETALLDAOUTPUTRESPONSE_H
#define CGX_DRIVER_MESSAGE_ROBOTGETALLDAOUTPUTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cgx_driver
{
template <class ContainerAllocator>
struct RobotGetAllDAOutputResponse_
{
  typedef RobotGetAllDAOutputResponse_<ContainerAllocator> Type;

  RobotGetAllDAOutputResponse_()
    : controllerDO()
    , controllerCO()
    , controllerAO()
    , toolDO()
    , ret(0)
    , message()  {
      controllerDO.assign(false);

      controllerCO.assign(false);

      controllerAO.assign(0.0);

      toolDO.assign(false);
  }
  RobotGetAllDAOutputResponse_(const ContainerAllocator& _alloc)
    : controllerDO()
    , controllerCO()
    , controllerAO()
    , toolDO()
    , ret(0)
    , message(_alloc)  {
  (void)_alloc;
      controllerDO.assign(false);

      controllerCO.assign(false);

      controllerAO.assign(0.0);

      toolDO.assign(false);
  }



   typedef boost::array<uint8_t, 8>  _controllerDO_type;
  _controllerDO_type controllerDO;

   typedef boost::array<uint8_t, 8>  _controllerCO_type;
  _controllerCO_type controllerCO;

   typedef boost::array<float, 1>  _controllerAO_type;
  _controllerAO_type controllerAO;

   typedef boost::array<uint8_t, 2>  _toolDO_type;
  _toolDO_type toolDO;

   typedef int16_t _ret_type;
  _ret_type ret;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotGetAllDAOutputResponse_

typedef ::cgx_driver::RobotGetAllDAOutputResponse_<std::allocator<void> > RobotGetAllDAOutputResponse;

typedef boost::shared_ptr< ::cgx_driver::RobotGetAllDAOutputResponse > RobotGetAllDAOutputResponsePtr;
typedef boost::shared_ptr< ::cgx_driver::RobotGetAllDAOutputResponse const> RobotGetAllDAOutputResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator2> & rhs)
{
  return lhs.controllerDO == rhs.controllerDO &&
    lhs.controllerCO == rhs.controllerCO &&
    lhs.controllerAO == rhs.controllerAO &&
    lhs.toolDO == rhs.toolDO &&
    lhs.ret == rhs.ret &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cgx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fdb3ecd52fd607089bccc8ca9c27eda0";
  }

  static const char* value(const ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfdb3ecd52fd60708ULL;
  static const uint64_t static_value2 = 0x9bccc8ca9c27eda0ULL;
};

template<class ContainerAllocator>
struct DataType< ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cgx_driver/RobotGetAllDAOutputResponse";
  }

  static const char* value(const ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[8] controllerDO\n"
"bool[8] controllerCO\n"
"float32[1] controllerAO\n"
"bool[2] toolDO\n"
"int16 ret\n"
"string message\n"
;
  }

  static const char* value(const ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controllerDO);
      stream.next(m.controllerCO);
      stream.next(m.controllerAO);
      stream.next(m.toolDO);
      stream.next(m.ret);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotGetAllDAOutputResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cgx_driver::RobotGetAllDAOutputResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "controllerDO: ";
    if (v.controllerDO.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.controllerDO.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.controllerDO[i]);
    }
    if (v.controllerDO.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "controllerCO: ";
    if (v.controllerCO.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.controllerCO.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.controllerCO[i]);
    }
    if (v.controllerCO.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "controllerAO: ";
    if (v.controllerAO.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.controllerAO.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.controllerAO[i]);
    }
    if (v.controllerAO.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "toolDO: ";
    if (v.toolDO.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.toolDO.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.toolDO[i]);
    }
    if (v.toolDO.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ret: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ret);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTGETALLDAOUTPUTRESPONSE_H
