// Generated by gencpp from file cgx_driver/RobotStateCurrentRequest.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTSTATECURRENTREQUEST_H
#define CGX_DRIVER_MESSAGE_ROBOTSTATECURRENTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cgx_driver
{
template <class ContainerAllocator>
struct RobotStateCurrentRequest_
{
  typedef RobotStateCurrentRequest_<ContainerAllocator> Type;

  RobotStateCurrentRequest_()
    {
    }
  RobotStateCurrentRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStateCurrentRequest_

typedef ::cgx_driver::RobotStateCurrentRequest_<std::allocator<void> > RobotStateCurrentRequest;

typedef boost::shared_ptr< ::cgx_driver::RobotStateCurrentRequest > RobotStateCurrentRequestPtr;
typedef boost::shared_ptr< ::cgx_driver::RobotStateCurrentRequest const> RobotStateCurrentRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace cgx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cgx_driver/RobotStateCurrentRequest";
  }

  static const char* value(const ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# RobotStateCurrent.srv\n"
;
  }

  static const char* value(const ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStateCurrentRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::cgx_driver::RobotStateCurrentRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTSTATECURRENTREQUEST_H
