// Generated by gencpp from file cgx_driver/RobotStateSpeed.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTSTATESPEED_H
#define CGX_DRIVER_MESSAGE_ROBOTSTATESPEED_H

#include <ros/service_traits.h>


#include <cgx_driver/RobotStateSpeedRequest.h>
#include <cgx_driver/RobotStateSpeedResponse.h>


namespace cgx_driver
{

struct RobotStateSpeed
{

typedef RobotStateSpeedRequest Request;
typedef RobotStateSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotStateSpeed
} // namespace cgx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cgx_driver::RobotStateSpeed > {
  static const char* value()
  {
    return "d7a84a591a1b34f702caf7415737a9ce";
  }

  static const char* value(const ::cgx_driver::RobotStateSpeed&) { return value(); }
};

template<>
struct DataType< ::cgx_driver::RobotStateSpeed > {
  static const char* value()
  {
    return "cgx_driver/RobotStateSpeed";
  }

  static const char* value(const ::cgx_driver::RobotStateSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::cgx_driver::RobotStateSpeedRequest> should match
// service_traits::MD5Sum< ::cgx_driver::RobotStateSpeed >
template<>
struct MD5Sum< ::cgx_driver::RobotStateSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotStateSpeed >::value();
  }
  static const char* value(const ::cgx_driver::RobotStateSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotStateSpeedRequest> should match
// service_traits::DataType< ::cgx_driver::RobotStateSpeed >
template<>
struct DataType< ::cgx_driver::RobotStateSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotStateSpeed >::value();
  }
  static const char* value(const ::cgx_driver::RobotStateSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cgx_driver::RobotStateSpeedResponse> should match
// service_traits::MD5Sum< ::cgx_driver::RobotStateSpeed >
template<>
struct MD5Sum< ::cgx_driver::RobotStateSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotStateSpeed >::value();
  }
  static const char* value(const ::cgx_driver::RobotStateSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotStateSpeedResponse> should match
// service_traits::DataType< ::cgx_driver::RobotStateSpeed >
template<>
struct DataType< ::cgx_driver::RobotStateSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotStateSpeed >::value();
  }
  static const char* value(const ::cgx_driver::RobotStateSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTSTATESPEED_H
