// Generated by gencpp from file cgx_driver/RobotMoveCircle.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTMOVECIRCLE_H
#define CGX_DRIVER_MESSAGE_ROBOTMOVECIRCLE_H

#include <ros/service_traits.h>


#include <cgx_driver/RobotMoveCircleRequest.h>
#include <cgx_driver/RobotMoveCircleResponse.h>


namespace cgx_driver
{

struct RobotMoveCircle
{

typedef RobotMoveCircleRequest Request;
typedef RobotMoveCircleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotMoveCircle
} // namespace cgx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cgx_driver::RobotMoveCircle > {
  static const char* value()
  {
    return "f04f1ce85f111cec2d880bee47b328ac";
  }

  static const char* value(const ::cgx_driver::RobotMoveCircle&) { return value(); }
};

template<>
struct DataType< ::cgx_driver::RobotMoveCircle > {
  static const char* value()
  {
    return "cgx_driver/RobotMoveCircle";
  }

  static const char* value(const ::cgx_driver::RobotMoveCircle&) { return value(); }
};


// service_traits::MD5Sum< ::cgx_driver::RobotMoveCircleRequest> should match
// service_traits::MD5Sum< ::cgx_driver::RobotMoveCircle >
template<>
struct MD5Sum< ::cgx_driver::RobotMoveCircleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotMoveCircle >::value();
  }
  static const char* value(const ::cgx_driver::RobotMoveCircleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotMoveCircleRequest> should match
// service_traits::DataType< ::cgx_driver::RobotMoveCircle >
template<>
struct DataType< ::cgx_driver::RobotMoveCircleRequest>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotMoveCircle >::value();
  }
  static const char* value(const ::cgx_driver::RobotMoveCircleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cgx_driver::RobotMoveCircleResponse> should match
// service_traits::MD5Sum< ::cgx_driver::RobotMoveCircle >
template<>
struct MD5Sum< ::cgx_driver::RobotMoveCircleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotMoveCircle >::value();
  }
  static const char* value(const ::cgx_driver::RobotMoveCircleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotMoveCircleResponse> should match
// service_traits::DataType< ::cgx_driver::RobotMoveCircle >
template<>
struct DataType< ::cgx_driver::RobotMoveCircleResponse>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotMoveCircle >::value();
  }
  static const char* value(const ::cgx_driver::RobotMoveCircleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTMOVECIRCLE_H
