// Generated by gencpp from file cgx_driver/RobotGetAllDAOutput.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTGETALLDAOUTPUT_H
#define CGX_DRIVER_MESSAGE_ROBOTGETALLDAOUTPUT_H

#include <ros/service_traits.h>


#include <cgx_driver/RobotGetAllDAOutputRequest.h>
#include <cgx_driver/RobotGetAllDAOutputResponse.h>


namespace cgx_driver
{

struct RobotGetAllDAOutput
{

typedef RobotGetAllDAOutputRequest Request;
typedef RobotGetAllDAOutputResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotGetAllDAOutput
} // namespace cgx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cgx_driver::RobotGetAllDAOutput > {
  static const char* value()
  {
    return "fdb3ecd52fd607089bccc8ca9c27eda0";
  }

  static const char* value(const ::cgx_driver::RobotGetAllDAOutput&) { return value(); }
};

template<>
struct DataType< ::cgx_driver::RobotGetAllDAOutput > {
  static const char* value()
  {
    return "cgx_driver/RobotGetAllDAOutput";
  }

  static const char* value(const ::cgx_driver::RobotGetAllDAOutput&) { return value(); }
};


// service_traits::MD5Sum< ::cgx_driver::RobotGetAllDAOutputRequest> should match
// service_traits::MD5Sum< ::cgx_driver::RobotGetAllDAOutput >
template<>
struct MD5Sum< ::cgx_driver::RobotGetAllDAOutputRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotGetAllDAOutput >::value();
  }
  static const char* value(const ::cgx_driver::RobotGetAllDAOutputRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotGetAllDAOutputRequest> should match
// service_traits::DataType< ::cgx_driver::RobotGetAllDAOutput >
template<>
struct DataType< ::cgx_driver::RobotGetAllDAOutputRequest>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotGetAllDAOutput >::value();
  }
  static const char* value(const ::cgx_driver::RobotGetAllDAOutputRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cgx_driver::RobotGetAllDAOutputResponse> should match
// service_traits::MD5Sum< ::cgx_driver::RobotGetAllDAOutput >
template<>
struct MD5Sum< ::cgx_driver::RobotGetAllDAOutputResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotGetAllDAOutput >::value();
  }
  static const char* value(const ::cgx_driver::RobotGetAllDAOutputResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotGetAllDAOutputResponse> should match
// service_traits::DataType< ::cgx_driver::RobotGetAllDAOutput >
template<>
struct DataType< ::cgx_driver::RobotGetAllDAOutputResponse>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotGetAllDAOutput >::value();
  }
  static const char* value(const ::cgx_driver::RobotGetAllDAOutputResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTGETALLDAOUTPUT_H
