// Generated by gencpp from file cgx_driver/RobotSetAnalogIOStateRequest.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTSETANALOGIOSTATEREQUEST_H
#define CGX_DRIVER_MESSAGE_ROBOTSETANALOGIOSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cgx_driver
{
template <class ContainerAllocator>
struct RobotSetAnalogIOStateRequest_
{
  typedef RobotSetAnalogIOStateRequest_<ContainerAllocator> Type;

  RobotSetAnalogIOStateRequest_()
    : index(0)
    , value(0.0)  {
    }
  RobotSetAnalogIOStateRequest_(const ContainerAllocator& _alloc)
    : index(0)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _index_type;
  _index_type index;

   typedef double _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotSetAnalogIOStateRequest_

typedef ::cgx_driver::RobotSetAnalogIOStateRequest_<std::allocator<void> > RobotSetAnalogIOStateRequest;

typedef boost::shared_ptr< ::cgx_driver::RobotSetAnalogIOStateRequest > RobotSetAnalogIOStateRequestPtr;
typedef boost::shared_ptr< ::cgx_driver::RobotSetAnalogIOStateRequest const> RobotSetAnalogIOStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cgx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12eafa6260d7544e3cc5c420df994a5f";
  }

  static const char* value(const ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12eafa6260d7544eULL;
  static const uint64_t static_value2 = 0x3cc5c420df994a5fULL;
};

template<class ContainerAllocator>
struct DataType< ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cgx_driver/RobotSetAnalogIOStateRequest";
  }

  static const char* value(const ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# RobotSetAnalogIOState.srv\n"
"int32 index\n"
"float64 value \n"
;
  }

  static const char* value(const ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotSetAnalogIOStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cgx_driver::RobotSetAnalogIOStateRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTSETANALOGIOSTATEREQUEST_H
