// Generated by gencpp from file cgx_driver/RobotStop.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTSTOP_H
#define CGX_DRIVER_MESSAGE_ROBOTSTOP_H

#include <ros/service_traits.h>


#include <cgx_driver/RobotStopRequest.h>
#include <cgx_driver/RobotStopResponse.h>


namespace cgx_driver
{

struct RobotStop
{

typedef RobotStopRequest Request;
typedef RobotStopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotStop
} // namespace cgx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cgx_driver::RobotStop > {
  static const char* value()
  {
    return "41f8ff55f84d1a1a88561afaab58a98f";
  }

  static const char* value(const ::cgx_driver::RobotStop&) { return value(); }
};

template<>
struct DataType< ::cgx_driver::RobotStop > {
  static const char* value()
  {
    return "cgx_driver/RobotStop";
  }

  static const char* value(const ::cgx_driver::RobotStop&) { return value(); }
};


// service_traits::MD5Sum< ::cgx_driver::RobotStopRequest> should match
// service_traits::MD5Sum< ::cgx_driver::RobotStop >
template<>
struct MD5Sum< ::cgx_driver::RobotStopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotStop >::value();
  }
  static const char* value(const ::cgx_driver::RobotStopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotStopRequest> should match
// service_traits::DataType< ::cgx_driver::RobotStop >
template<>
struct DataType< ::cgx_driver::RobotStopRequest>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotStop >::value();
  }
  static const char* value(const ::cgx_driver::RobotStopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cgx_driver::RobotStopResponse> should match
// service_traits::MD5Sum< ::cgx_driver::RobotStop >
template<>
struct MD5Sum< ::cgx_driver::RobotStopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotStop >::value();
  }
  static const char* value(const ::cgx_driver::RobotStopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotStopResponse> should match
// service_traits::DataType< ::cgx_driver::RobotStop >
template<>
struct DataType< ::cgx_driver::RobotStopResponse>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotStop >::value();
  }
  static const char* value(const ::cgx_driver::RobotStopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTSTOP_H
