// Generated by gencpp from file cgx_driver/RobotSetAnalogIOState.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTSETANALOGIOSTATE_H
#define CGX_DRIVER_MESSAGE_ROBOTSETANALOGIOSTATE_H

#include <ros/service_traits.h>


#include <cgx_driver/RobotSetAnalogIOStateRequest.h>
#include <cgx_driver/RobotSetAnalogIOStateResponse.h>


namespace cgx_driver
{

struct RobotSetAnalogIOState
{

typedef RobotSetAnalogIOStateRequest Request;
typedef RobotSetAnalogIOStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotSetAnalogIOState
} // namespace cgx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cgx_driver::RobotSetAnalogIOState > {
  static const char* value()
  {
    return "5228b462be2cb5ab024a8f7c3e4bc55e";
  }

  static const char* value(const ::cgx_driver::RobotSetAnalogIOState&) { return value(); }
};

template<>
struct DataType< ::cgx_driver::RobotSetAnalogIOState > {
  static const char* value()
  {
    return "cgx_driver/RobotSetAnalogIOState";
  }

  static const char* value(const ::cgx_driver::RobotSetAnalogIOState&) { return value(); }
};


// service_traits::MD5Sum< ::cgx_driver::RobotSetAnalogIOStateRequest> should match
// service_traits::MD5Sum< ::cgx_driver::RobotSetAnalogIOState >
template<>
struct MD5Sum< ::cgx_driver::RobotSetAnalogIOStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotSetAnalogIOState >::value();
  }
  static const char* value(const ::cgx_driver::RobotSetAnalogIOStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotSetAnalogIOStateRequest> should match
// service_traits::DataType< ::cgx_driver::RobotSetAnalogIOState >
template<>
struct DataType< ::cgx_driver::RobotSetAnalogIOStateRequest>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotSetAnalogIOState >::value();
  }
  static const char* value(const ::cgx_driver::RobotSetAnalogIOStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cgx_driver::RobotSetAnalogIOStateResponse> should match
// service_traits::MD5Sum< ::cgx_driver::RobotSetAnalogIOState >
template<>
struct MD5Sum< ::cgx_driver::RobotSetAnalogIOStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotSetAnalogIOState >::value();
  }
  static const char* value(const ::cgx_driver::RobotSetAnalogIOStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotSetAnalogIOStateResponse> should match
// service_traits::DataType< ::cgx_driver::RobotSetAnalogIOState >
template<>
struct DataType< ::cgx_driver::RobotSetAnalogIOStateResponse>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotSetAnalogIOState >::value();
  }
  static const char* value(const ::cgx_driver::RobotSetAnalogIOStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTSETANALOGIOSTATE_H
