// Generated by gencpp from file cgx_driver/RobotSetDigitalIOStateRequest.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTSETDIGITALIOSTATEREQUEST_H
#define CGX_DRIVER_MESSAGE_ROBOTSETDIGITALIOSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cgx_driver
{
template <class ContainerAllocator>
struct RobotSetDigitalIOStateRequest_
{
  typedef RobotSetDigitalIOStateRequest_<ContainerAllocator> Type;

  RobotSetDigitalIOStateRequest_()
    : index(0)
    , value(false)  {
    }
  RobotSetDigitalIOStateRequest_(const ContainerAllocator& _alloc)
    : index(0)
    , value(false)  {
  (void)_alloc;
    }



   typedef int32_t _index_type;
  _index_type index;

   typedef uint8_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotSetDigitalIOStateRequest_

typedef ::cgx_driver::RobotSetDigitalIOStateRequest_<std::allocator<void> > RobotSetDigitalIOStateRequest;

typedef boost::shared_ptr< ::cgx_driver::RobotSetDigitalIOStateRequest > RobotSetDigitalIOStateRequestPtr;
typedef boost::shared_ptr< ::cgx_driver::RobotSetDigitalIOStateRequest const> RobotSetDigitalIOStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cgx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "403c25936abf9651ea2ad8a9e81c85e8";
  }

  static const char* value(const ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x403c25936abf9651ULL;
  static const uint64_t static_value2 = 0xea2ad8a9e81c85e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cgx_driver/RobotSetDigitalIOStateRequest";
  }

  static const char* value(const ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# RobotSetDigitalIOState.srv\n"
"int32 index\n"
"bool value \n"
;
  }

  static const char* value(const ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotSetDigitalIOStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cgx_driver::RobotSetDigitalIOStateRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTSETDIGITALIOSTATEREQUEST_H
