// Generated by gencpp from file cgx_driver/RobotGetAnalogIOStateRequest.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTGETANALOGIOSTATEREQUEST_H
#define CGX_DRIVER_MESSAGE_ROBOTGETANALOGIOSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cgx_driver
{
template <class ContainerAllocator>
struct RobotGetAnalogIOStateRequest_
{
  typedef RobotGetAnalogIOStateRequest_<ContainerAllocator> Type;

  RobotGetAnalogIOStateRequest_()
    : index(0)  {
    }
  RobotGetAnalogIOStateRequest_(const ContainerAllocator& _alloc)
    : index(0)  {
  (void)_alloc;
    }



   typedef int32_t _index_type;
  _index_type index;





  typedef boost::shared_ptr< ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotGetAnalogIOStateRequest_

typedef ::cgx_driver::RobotGetAnalogIOStateRequest_<std::allocator<void> > RobotGetAnalogIOStateRequest;

typedef boost::shared_ptr< ::cgx_driver::RobotGetAnalogIOStateRequest > RobotGetAnalogIOStateRequestPtr;
typedef boost::shared_ptr< ::cgx_driver::RobotGetAnalogIOStateRequest const> RobotGetAnalogIOStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cgx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "483eea06cdc3e559421ee31116d0f3b9";
  }

  static const char* value(const ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x483eea06cdc3e559ULL;
  static const uint64_t static_value2 = 0x421ee31116d0f3b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cgx_driver/RobotGetAnalogIOStateRequest";
  }

  static const char* value(const ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# RobotGetAnalogIOState.srv\n"
"int32 index\n"
;
  }

  static const char* value(const ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotGetAnalogIOStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cgx_driver::RobotGetAnalogIOStateRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTGETANALOGIOSTATEREQUEST_H
