// Generated by gencpp from file cgx_driver/RobotStateAcceleration.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTSTATEACCELERATION_H
#define CGX_DRIVER_MESSAGE_ROBOTSTATEACCELERATION_H

#include <ros/service_traits.h>


#include <cgx_driver/RobotStateAccelerationRequest.h>
#include <cgx_driver/RobotStateAccelerationResponse.h>


namespace cgx_driver
{

struct RobotStateAcceleration
{

typedef RobotStateAccelerationRequest Request;
typedef RobotStateAccelerationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotStateAcceleration
} // namespace cgx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cgx_driver::RobotStateAcceleration > {
  static const char* value()
  {
    return "d990f27bdf8ca210513247342e9b6737";
  }

  static const char* value(const ::cgx_driver::RobotStateAcceleration&) { return value(); }
};

template<>
struct DataType< ::cgx_driver::RobotStateAcceleration > {
  static const char* value()
  {
    return "cgx_driver/RobotStateAcceleration";
  }

  static const char* value(const ::cgx_driver::RobotStateAcceleration&) { return value(); }
};


// service_traits::MD5Sum< ::cgx_driver::RobotStateAccelerationRequest> should match
// service_traits::MD5Sum< ::cgx_driver::RobotStateAcceleration >
template<>
struct MD5Sum< ::cgx_driver::RobotStateAccelerationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotStateAcceleration >::value();
  }
  static const char* value(const ::cgx_driver::RobotStateAccelerationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotStateAccelerationRequest> should match
// service_traits::DataType< ::cgx_driver::RobotStateAcceleration >
template<>
struct DataType< ::cgx_driver::RobotStateAccelerationRequest>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotStateAcceleration >::value();
  }
  static const char* value(const ::cgx_driver::RobotStateAccelerationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cgx_driver::RobotStateAccelerationResponse> should match
// service_traits::MD5Sum< ::cgx_driver::RobotStateAcceleration >
template<>
struct MD5Sum< ::cgx_driver::RobotStateAccelerationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotStateAcceleration >::value();
  }
  static const char* value(const ::cgx_driver::RobotStateAccelerationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotStateAccelerationResponse> should match
// service_traits::DataType< ::cgx_driver::RobotStateAcceleration >
template<>
struct DataType< ::cgx_driver::RobotStateAccelerationResponse>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotStateAcceleration >::value();
  }
  static const char* value(const ::cgx_driver::RobotStateAccelerationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTSTATEACCELERATION_H
