// Generated by gencpp from file cgx_driver/RobotStatePose.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTSTATEPOSE_H
#define CGX_DRIVER_MESSAGE_ROBOTSTATEPOSE_H

#include <ros/service_traits.h>


#include <cgx_driver/RobotStatePoseRequest.h>
#include <cgx_driver/RobotStatePoseResponse.h>


namespace cgx_driver
{

struct RobotStatePose
{

typedef RobotStatePoseRequest Request;
typedef RobotStatePoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotStatePose
} // namespace cgx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cgx_driver::RobotStatePose > {
  static const char* value()
  {
    return "d934b828b167df2066e86054919aa285";
  }

  static const char* value(const ::cgx_driver::RobotStatePose&) { return value(); }
};

template<>
struct DataType< ::cgx_driver::RobotStatePose > {
  static const char* value()
  {
    return "cgx_driver/RobotStatePose";
  }

  static const char* value(const ::cgx_driver::RobotStatePose&) { return value(); }
};


// service_traits::MD5Sum< ::cgx_driver::RobotStatePoseRequest> should match
// service_traits::MD5Sum< ::cgx_driver::RobotStatePose >
template<>
struct MD5Sum< ::cgx_driver::RobotStatePoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotStatePose >::value();
  }
  static const char* value(const ::cgx_driver::RobotStatePoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotStatePoseRequest> should match
// service_traits::DataType< ::cgx_driver::RobotStatePose >
template<>
struct DataType< ::cgx_driver::RobotStatePoseRequest>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotStatePose >::value();
  }
  static const char* value(const ::cgx_driver::RobotStatePoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cgx_driver::RobotStatePoseResponse> should match
// service_traits::MD5Sum< ::cgx_driver::RobotStatePose >
template<>
struct MD5Sum< ::cgx_driver::RobotStatePoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotStatePose >::value();
  }
  static const char* value(const ::cgx_driver::RobotStatePoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotStatePoseResponse> should match
// service_traits::DataType< ::cgx_driver::RobotStatePose >
template<>
struct DataType< ::cgx_driver::RobotStatePoseResponse>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotStatePose >::value();
  }
  static const char* value(const ::cgx_driver::RobotStatePoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTSTATEPOSE_H
