// Generated by gencpp from file cgx_driver/RobotStateSpeedResponse.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTSTATESPEEDRESPONSE_H
#define CGX_DRIVER_MESSAGE_ROBOTSTATESPEEDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cgx_driver
{
template <class ContainerAllocator>
struct RobotStateSpeedResponse_
{
  typedef RobotStateSpeedResponse_<ContainerAllocator> Type;

  RobotStateSpeedResponse_()
    : speed()
    , ret(0)
    , message()  {
      speed.assign(0.0);
  }
  RobotStateSpeedResponse_(const ContainerAllocator& _alloc)
    : speed()
    , ret(0)
    , message(_alloc)  {
  (void)_alloc;
      speed.assign(0.0);
  }



   typedef boost::array<double, 6>  _speed_type;
  _speed_type speed;

   typedef int32_t _ret_type;
  _ret_type ret;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStateSpeedResponse_

typedef ::cgx_driver::RobotStateSpeedResponse_<std::allocator<void> > RobotStateSpeedResponse;

typedef boost::shared_ptr< ::cgx_driver::RobotStateSpeedResponse > RobotStateSpeedResponsePtr;
typedef boost::shared_ptr< ::cgx_driver::RobotStateSpeedResponse const> RobotStateSpeedResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed &&
    lhs.ret == rhs.ret &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cgx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7a84a591a1b34f702caf7415737a9ce";
  }

  static const char* value(const ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7a84a591a1b34f7ULL;
  static const uint64_t static_value2 = 0x02caf7415737a9ceULL;
};

template<class ContainerAllocator>
struct DataType< ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cgx_driver/RobotStateSpeedResponse";
  }

  static const char* value(const ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[6] speed  \n"
"int32 ret        \n"
"string message   \n"
;
  }

  static const char* value(const ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.ret);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStateSpeedResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cgx_driver::RobotStateSpeedResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "speed: ";
    if (v.speed.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.speed.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.speed[i]);
    }
    if (v.speed.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ret: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ret);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTSTATESPEEDRESPONSE_H
