// Generated by gencpp from file cgx_driver/RobotGetDigitalIOStateResponse.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTGETDIGITALIOSTATERESPONSE_H
#define CGX_DRIVER_MESSAGE_ROBOTGETDIGITALIOSTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cgx_driver
{
template <class ContainerAllocator>
struct RobotGetDigitalIOStateResponse_
{
  typedef RobotGetDigitalIOStateResponse_<ContainerAllocator> Type;

  RobotGetDigitalIOStateResponse_()
    : value(false)
    , ret(0)
    , message()  {
    }
  RobotGetDigitalIOStateResponse_(const ContainerAllocator& _alloc)
    : value(false)
    , ret(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;

   typedef int32_t _ret_type;
  _ret_type ret;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotGetDigitalIOStateResponse_

typedef ::cgx_driver::RobotGetDigitalIOStateResponse_<std::allocator<void> > RobotGetDigitalIOStateResponse;

typedef boost::shared_ptr< ::cgx_driver::RobotGetDigitalIOStateResponse > RobotGetDigitalIOStateResponsePtr;
typedef boost::shared_ptr< ::cgx_driver::RobotGetDigitalIOStateResponse const> RobotGetDigitalIOStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value &&
    lhs.ret == rhs.ret &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cgx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe18d5a5a094d574ae7b7f7af56315c9";
  }

  static const char* value(const ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe18d5a5a094d574ULL;
  static const uint64_t static_value2 = 0xae7b7f7af56315c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cgx_driver/RobotGetDigitalIOStateResponse";
  }

  static const char* value(const ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool value \n"
"int32 ret        # 返回状态码\n"
"string message   # 返回信息\n"
;
  }

  static const char* value(const ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
      stream.next(m.ret);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotGetDigitalIOStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cgx_driver::RobotGetDigitalIOStateResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ret: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ret);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTGETDIGITALIOSTATERESPONSE_H
