// Generated by gencpp from file cgx_driver/RobotSetDigitalIOState.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTSETDIGITALIOSTATE_H
#define CGX_DRIVER_MESSAGE_ROBOTSETDIGITALIOSTATE_H

#include <ros/service_traits.h>


#include <cgx_driver/RobotSetDigitalIOStateRequest.h>
#include <cgx_driver/RobotSetDigitalIOStateResponse.h>


namespace cgx_driver
{

struct RobotSetDigitalIOState
{

typedef RobotSetDigitalIOStateRequest Request;
typedef RobotSetDigitalIOStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotSetDigitalIOState
} // namespace cgx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cgx_driver::RobotSetDigitalIOState > {
  static const char* value()
  {
    return "275e05a98203a4248140629998ca7ca5";
  }

  static const char* value(const ::cgx_driver::RobotSetDigitalIOState&) { return value(); }
};

template<>
struct DataType< ::cgx_driver::RobotSetDigitalIOState > {
  static const char* value()
  {
    return "cgx_driver/RobotSetDigitalIOState";
  }

  static const char* value(const ::cgx_driver::RobotSetDigitalIOState&) { return value(); }
};


// service_traits::MD5Sum< ::cgx_driver::RobotSetDigitalIOStateRequest> should match
// service_traits::MD5Sum< ::cgx_driver::RobotSetDigitalIOState >
template<>
struct MD5Sum< ::cgx_driver::RobotSetDigitalIOStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotSetDigitalIOState >::value();
  }
  static const char* value(const ::cgx_driver::RobotSetDigitalIOStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotSetDigitalIOStateRequest> should match
// service_traits::DataType< ::cgx_driver::RobotSetDigitalIOState >
template<>
struct DataType< ::cgx_driver::RobotSetDigitalIOStateRequest>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotSetDigitalIOState >::value();
  }
  static const char* value(const ::cgx_driver::RobotSetDigitalIOStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cgx_driver::RobotSetDigitalIOStateResponse> should match
// service_traits::MD5Sum< ::cgx_driver::RobotSetDigitalIOState >
template<>
struct MD5Sum< ::cgx_driver::RobotSetDigitalIOStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotSetDigitalIOState >::value();
  }
  static const char* value(const ::cgx_driver::RobotSetDigitalIOStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotSetDigitalIOStateResponse> should match
// service_traits::DataType< ::cgx_driver::RobotSetDigitalIOState >
template<>
struct DataType< ::cgx_driver::RobotSetDigitalIOStateResponse>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotSetDigitalIOState >::value();
  }
  static const char* value(const ::cgx_driver::RobotSetDigitalIOStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTSETDIGITALIOSTATE_H
