// Generated by gencpp from file cgx_driver/RobotGetAllDAInputResponse.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTGETALLDAINPUTRESPONSE_H
#define CGX_DRIVER_MESSAGE_ROBOTGETALLDAINPUTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cgx_driver
{
template <class ContainerAllocator>
struct RobotGetAllDAInputResponse_
{
  typedef RobotGetAllDAInputResponse_<ContainerAllocator> Type;

  RobotGetAllDAInputResponse_()
    : controllerDI()
    , controllerCI()
    , controllerAI()
    , toolDI()
    , toolAI()
    , ret(0)
    , message()  {
      controllerDI.assign(false);

      controllerCI.assign(false);

      controllerAI.assign(0.0);

      toolDI.assign(false);

      toolAI.assign(0.0);
  }
  RobotGetAllDAInputResponse_(const ContainerAllocator& _alloc)
    : controllerDI()
    , controllerCI()
    , controllerAI()
    , toolDI()
    , toolAI()
    , ret(0)
    , message(_alloc)  {
  (void)_alloc;
      controllerDI.assign(false);

      controllerCI.assign(false);

      controllerAI.assign(0.0);

      toolDI.assign(false);

      toolAI.assign(0.0);
  }



   typedef boost::array<uint8_t, 8>  _controllerDI_type;
  _controllerDI_type controllerDI;

   typedef boost::array<uint8_t, 8>  _controllerCI_type;
  _controllerCI_type controllerCI;

   typedef boost::array<float, 3>  _controllerAI_type;
  _controllerAI_type controllerAI;

   typedef boost::array<uint8_t, 2>  _toolDI_type;
  _toolDI_type toolDI;

   typedef boost::array<float, 2>  _toolAI_type;
  _toolAI_type toolAI;

   typedef int16_t _ret_type;
  _ret_type ret;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotGetAllDAInputResponse_

typedef ::cgx_driver::RobotGetAllDAInputResponse_<std::allocator<void> > RobotGetAllDAInputResponse;

typedef boost::shared_ptr< ::cgx_driver::RobotGetAllDAInputResponse > RobotGetAllDAInputResponsePtr;
typedef boost::shared_ptr< ::cgx_driver::RobotGetAllDAInputResponse const> RobotGetAllDAInputResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator2> & rhs)
{
  return lhs.controllerDI == rhs.controllerDI &&
    lhs.controllerCI == rhs.controllerCI &&
    lhs.controllerAI == rhs.controllerAI &&
    lhs.toolDI == rhs.toolDI &&
    lhs.toolAI == rhs.toolAI &&
    lhs.ret == rhs.ret &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cgx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba808cbeaab4420830cd2c51b834403";
  }

  static const char* value(const ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba808cbeaab4420ULL;
  static const uint64_t static_value2 = 0x830cd2c51b834403ULL;
};

template<class ContainerAllocator>
struct DataType< ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cgx_driver/RobotGetAllDAInputResponse";
  }

  static const char* value(const ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[8] controllerDI\n"
"bool[8] controllerCI\n"
"float32[3] controllerAI\n"
"bool[2] toolDI\n"
"float32[2] toolAI\n"
"int16 ret\n"
"string message\n"
;
  }

  static const char* value(const ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controllerDI);
      stream.next(m.controllerCI);
      stream.next(m.controllerAI);
      stream.next(m.toolDI);
      stream.next(m.toolAI);
      stream.next(m.ret);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotGetAllDAInputResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cgx_driver::RobotGetAllDAInputResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "controllerDI: ";
    if (v.controllerDI.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.controllerDI.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.controllerDI[i]);
    }
    if (v.controllerDI.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "controllerCI: ";
    if (v.controllerCI.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.controllerCI.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.controllerCI[i]);
    }
    if (v.controllerCI.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "controllerAI: ";
    if (v.controllerAI.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.controllerAI.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.controllerAI[i]);
    }
    if (v.controllerAI.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "toolDI: ";
    if (v.toolDI.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.toolDI.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.toolDI[i]);
    }
    if (v.toolDI.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "toolAI: ";
    if (v.toolAI.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.toolAI.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.toolAI[i]);
    }
    if (v.toolAI.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ret: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ret);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTGETALLDAINPUTRESPONSE_H
