// Generated by gencpp from file cgx_driver/RobotSetDigitalIOStateResponse.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTSETDIGITALIOSTATERESPONSE_H
#define CGX_DRIVER_MESSAGE_ROBOTSETDIGITALIOSTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cgx_driver
{
template <class ContainerAllocator>
struct RobotSetDigitalIOStateResponse_
{
  typedef RobotSetDigitalIOStateResponse_<ContainerAllocator> Type;

  RobotSetDigitalIOStateResponse_()
    : ret(0)
    , message()  {
    }
  RobotSetDigitalIOStateResponse_(const ContainerAllocator& _alloc)
    : ret(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _ret_type;
  _ret_type ret;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotSetDigitalIOStateResponse_

typedef ::cgx_driver::RobotSetDigitalIOStateResponse_<std::allocator<void> > RobotSetDigitalIOStateResponse;

typedef boost::shared_ptr< ::cgx_driver::RobotSetDigitalIOStateResponse > RobotSetDigitalIOStateResponsePtr;
typedef boost::shared_ptr< ::cgx_driver::RobotSetDigitalIOStateResponse const> RobotSetDigitalIOStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ret == rhs.ret &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cgx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "afdb845140e2f05f77c770110f12be2b";
  }

  static const char* value(const ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xafdb845140e2f05fULL;
  static const uint64_t static_value2 = 0x77c770110f12be2bULL;
};

template<class ContainerAllocator>
struct DataType< ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cgx_driver/RobotSetDigitalIOStateResponse";
  }

  static const char* value(const ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ret        # 返回状态码\n"
"string message   # 返回信息\n"
;
  }

  static const char* value(const ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotSetDigitalIOStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cgx_driver::RobotSetDigitalIOStateResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "ret: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ret);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTSETDIGITALIOSTATERESPONSE_H
