// Generated by gencpp from file cgx_driver/RobotStopRequest.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTSTOPREQUEST_H
#define CGX_DRIVER_MESSAGE_ROBOTSTOPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cgx_driver
{
template <class ContainerAllocator>
struct RobotStopRequest_
{
  typedef RobotStopRequest_<ContainerAllocator> Type;

  RobotStopRequest_()
    : moveType()  {
    }
  RobotStopRequest_(const ContainerAllocator& _alloc)
    : moveType(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _moveType_type;
  _moveType_type moveType;





  typedef boost::shared_ptr< ::cgx_driver::RobotStopRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cgx_driver::RobotStopRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStopRequest_

typedef ::cgx_driver::RobotStopRequest_<std::allocator<void> > RobotStopRequest;

typedef boost::shared_ptr< ::cgx_driver::RobotStopRequest > RobotStopRequestPtr;
typedef boost::shared_ptr< ::cgx_driver::RobotStopRequest const> RobotStopRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cgx_driver::RobotStopRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cgx_driver::RobotStopRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cgx_driver::RobotStopRequest_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotStopRequest_<ContainerAllocator2> & rhs)
{
  return lhs.moveType == rhs.moveType;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cgx_driver::RobotStopRequest_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotStopRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cgx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotStopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotStopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotStopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotStopRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotStopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotStopRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cgx_driver::RobotStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b28fc52265fa462da2479a3f45281aeb";
  }

  static const char* value(const ::cgx_driver::RobotStopRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb28fc52265fa462dULL;
  static const uint64_t static_value2 = 0xa2479a3f45281aebULL;
};

template<class ContainerAllocator>
struct DataType< ::cgx_driver::RobotStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cgx_driver/RobotStopRequest";
  }

  static const char* value(const ::cgx_driver::RobotStopRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cgx_driver::RobotStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# RobotStop.srv\n"
"string moveType \n"
;
  }

  static const char* value(const ::cgx_driver::RobotStopRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cgx_driver::RobotStopRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.moveType);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStopRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cgx_driver::RobotStopRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cgx_driver::RobotStopRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "moveType: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.moveType);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTSTOPREQUEST_H
