// Generated by gencpp from file cgx_driver/RobotStatePoseResponse.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTSTATEPOSERESPONSE_H
#define CGX_DRIVER_MESSAGE_ROBOTSTATEPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cgx_driver
{
template <class ContainerAllocator>
struct RobotStatePoseResponse_
{
  typedef RobotStatePoseResponse_<ContainerAllocator> Type;

  RobotStatePoseResponse_()
    : pose()
    , ret(0)
    , message()  {
      pose.assign(0.0);
  }
  RobotStatePoseResponse_(const ContainerAllocator& _alloc)
    : pose()
    , ret(0)
    , message(_alloc)  {
  (void)_alloc;
      pose.assign(0.0);
  }



   typedef boost::array<double, 6>  _pose_type;
  _pose_type pose;

   typedef int32_t _ret_type;
  _ret_type ret;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStatePoseResponse_

typedef ::cgx_driver::RobotStatePoseResponse_<std::allocator<void> > RobotStatePoseResponse;

typedef boost::shared_ptr< ::cgx_driver::RobotStatePoseResponse > RobotStatePoseResponsePtr;
typedef boost::shared_ptr< ::cgx_driver::RobotStatePoseResponse const> RobotStatePoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.ret == rhs.ret &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cgx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d934b828b167df2066e86054919aa285";
  }

  static const char* value(const ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd934b828b167df20ULL;
  static const uint64_t static_value2 = 0x66e86054919aa285ULL;
};

template<class ContainerAllocator>
struct DataType< ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cgx_driver/RobotStatePoseResponse";
  }

  static const char* value(const ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[6] pose  # 返回的6维位姿数组\n"
"int32 ret        # 返回状态码\n"
"string message   # 返回信息\n"
;
  }

  static const char* value(const ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.ret);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStatePoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cgx_driver::RobotStatePoseResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    if (v.pose.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.pose[i]);
    }
    if (v.pose.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ret: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ret);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTSTATEPOSERESPONSE_H
