// Generated by gencpp from file cgx_driver/RobotStateCurrent.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTSTATECURRENT_H
#define CGX_DRIVER_MESSAGE_ROBOTSTATECURRENT_H

#include <ros/service_traits.h>


#include <cgx_driver/RobotStateCurrentRequest.h>
#include <cgx_driver/RobotStateCurrentResponse.h>


namespace cgx_driver
{

struct RobotStateCurrent
{

typedef RobotStateCurrentRequest Request;
typedef RobotStateCurrentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotStateCurrent
} // namespace cgx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cgx_driver::RobotStateCurrent > {
  static const char* value()
  {
    return "72a586880c39d961d06c55803979df7b";
  }

  static const char* value(const ::cgx_driver::RobotStateCurrent&) { return value(); }
};

template<>
struct DataType< ::cgx_driver::RobotStateCurrent > {
  static const char* value()
  {
    return "cgx_driver/RobotStateCurrent";
  }

  static const char* value(const ::cgx_driver::RobotStateCurrent&) { return value(); }
};


// service_traits::MD5Sum< ::cgx_driver::RobotStateCurrentRequest> should match
// service_traits::MD5Sum< ::cgx_driver::RobotStateCurrent >
template<>
struct MD5Sum< ::cgx_driver::RobotStateCurrentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotStateCurrent >::value();
  }
  static const char* value(const ::cgx_driver::RobotStateCurrentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotStateCurrentRequest> should match
// service_traits::DataType< ::cgx_driver::RobotStateCurrent >
template<>
struct DataType< ::cgx_driver::RobotStateCurrentRequest>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotStateCurrent >::value();
  }
  static const char* value(const ::cgx_driver::RobotStateCurrentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cgx_driver::RobotStateCurrentResponse> should match
// service_traits::MD5Sum< ::cgx_driver::RobotStateCurrent >
template<>
struct MD5Sum< ::cgx_driver::RobotStateCurrentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cgx_driver::RobotStateCurrent >::value();
  }
  static const char* value(const ::cgx_driver::RobotStateCurrentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cgx_driver::RobotStateCurrentResponse> should match
// service_traits::DataType< ::cgx_driver::RobotStateCurrent >
template<>
struct DataType< ::cgx_driver::RobotStateCurrentResponse>
{
  static const char* value()
  {
    return DataType< ::cgx_driver::RobotStateCurrent >::value();
  }
  static const char* value(const ::cgx_driver::RobotStateCurrentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTSTATECURRENT_H
