// Generated by gencpp from file cgx_driver/RobotMoveCircleRequest.msg
// DO NOT EDIT!


#ifndef CGX_DRIVER_MESSAGE_ROBOTMOVECIRCLEREQUEST_H
#define CGX_DRIVER_MESSAGE_ROBOTMOVECIRCLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cgx_driver
{
template <class ContainerAllocator>
struct RobotMoveCircleRequest_
{
  typedef RobotMoveCircleRequest_<ContainerAllocator> Type;

  RobotMoveCircleRequest_()
    : mid_pose()
    , mid_jointpos()
    , mid_speed()
    , mid_acc()
    , mid_coordinate_type()
    , mid_point_trans_type()
    , end_pose()
    , end_jointpos()
    , end_speed()
    , end_acc()
    , end_coordinate_type()
    , end_point_trans_type()
    , end_is_block(0)  {
    }
  RobotMoveCircleRequest_(const ContainerAllocator& _alloc)
    : mid_pose(_alloc)
    , mid_jointpos(_alloc)
    , mid_speed(_alloc)
    , mid_acc(_alloc)
    , mid_coordinate_type(_alloc)
    , mid_point_trans_type(_alloc)
    , end_pose(_alloc)
    , end_jointpos(_alloc)
    , end_speed(_alloc)
    , end_acc(_alloc)
    , end_coordinate_type(_alloc)
    , end_point_trans_type(_alloc)
    , end_is_block(0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _mid_pose_type;
  _mid_pose_type mid_pose;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _mid_jointpos_type;
  _mid_jointpos_type mid_jointpos;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _mid_speed_type;
  _mid_speed_type mid_speed;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _mid_acc_type;
  _mid_acc_type mid_acc;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mid_coordinate_type_type;
  _mid_coordinate_type_type mid_coordinate_type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mid_point_trans_type_type;
  _mid_point_trans_type_type mid_point_trans_type;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _end_pose_type;
  _end_pose_type end_pose;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _end_jointpos_type;
  _end_jointpos_type end_jointpos;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _end_speed_type;
  _end_speed_type end_speed;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _end_acc_type;
  _end_acc_type end_acc;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _end_coordinate_type_type;
  _end_coordinate_type_type end_coordinate_type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _end_point_trans_type_type;
  _end_point_trans_type_type end_point_trans_type;

   typedef int16_t _end_is_block_type;
  _end_is_block_type end_is_block;





  typedef boost::shared_ptr< ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotMoveCircleRequest_

typedef ::cgx_driver::RobotMoveCircleRequest_<std::allocator<void> > RobotMoveCircleRequest;

typedef boost::shared_ptr< ::cgx_driver::RobotMoveCircleRequest > RobotMoveCircleRequestPtr;
typedef boost::shared_ptr< ::cgx_driver::RobotMoveCircleRequest const> RobotMoveCircleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mid_pose == rhs.mid_pose &&
    lhs.mid_jointpos == rhs.mid_jointpos &&
    lhs.mid_speed == rhs.mid_speed &&
    lhs.mid_acc == rhs.mid_acc &&
    lhs.mid_coordinate_type == rhs.mid_coordinate_type &&
    lhs.mid_point_trans_type == rhs.mid_point_trans_type &&
    lhs.end_pose == rhs.end_pose &&
    lhs.end_jointpos == rhs.end_jointpos &&
    lhs.end_speed == rhs.end_speed &&
    lhs.end_acc == rhs.end_acc &&
    lhs.end_coordinate_type == rhs.end_coordinate_type &&
    lhs.end_point_trans_type == rhs.end_point_trans_type &&
    lhs.end_is_block == rhs.end_is_block;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator1> & lhs, const ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cgx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e534d24ab03721243e3de027b84b534";
  }

  static const char* value(const ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e534d24ab037212ULL;
  static const uint64_t static_value2 = 0x43e3de027b84b534ULL;
};

template<class ContainerAllocator>
struct DataType< ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cgx_driver/RobotMoveCircleRequest";
  }

  static const char* value(const ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# RobotMoveCircle.srv\n"
"float32[] mid_pose\n"
"float32[] mid_jointpos\n"
"float32[] mid_speed\n"
"float32[] mid_acc\n"
"string mid_coordinate_type\n"
"string mid_point_trans_type\n"
"float32[] end_pose\n"
"float32[] end_jointpos\n"
"float32[] end_speed\n"
"float32[] end_acc\n"
"string end_coordinate_type\n"
"string end_point_trans_type\n"
"int16 end_is_block\n"
;
  }

  static const char* value(const ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mid_pose);
      stream.next(m.mid_jointpos);
      stream.next(m.mid_speed);
      stream.next(m.mid_acc);
      stream.next(m.mid_coordinate_type);
      stream.next(m.mid_point_trans_type);
      stream.next(m.end_pose);
      stream.next(m.end_jointpos);
      stream.next(m.end_speed);
      stream.next(m.end_acc);
      stream.next(m.end_coordinate_type);
      stream.next(m.end_point_trans_type);
      stream.next(m.end_is_block);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotMoveCircleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cgx_driver::RobotMoveCircleRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "mid_pose: ";
    if (v.mid_pose.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.mid_pose.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.mid_pose[i]);
    }
    if (v.mid_pose.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mid_jointpos: ";
    if (v.mid_jointpos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.mid_jointpos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.mid_jointpos[i]);
    }
    if (v.mid_jointpos.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mid_speed: ";
    if (v.mid_speed.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.mid_speed.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.mid_speed[i]);
    }
    if (v.mid_speed.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mid_acc: ";
    if (v.mid_acc.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.mid_acc.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.mid_acc[i]);
    }
    if (v.mid_acc.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mid_coordinate_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mid_coordinate_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mid_point_trans_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mid_point_trans_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "end_pose: ";
    if (v.end_pose.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.end_pose.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.end_pose[i]);
    }
    if (v.end_pose.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "end_jointpos: ";
    if (v.end_jointpos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.end_jointpos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.end_jointpos[i]);
    }
    if (v.end_jointpos.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "end_speed: ";
    if (v.end_speed.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.end_speed.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.end_speed[i]);
    }
    if (v.end_speed.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "end_acc: ";
    if (v.end_acc.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.end_acc.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.end_acc[i]);
    }
    if (v.end_acc.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "end_coordinate_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.end_coordinate_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "end_point_trans_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.end_point_trans_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "end_is_block: ";
    Printer<int16_t>::stream(s, indent + "  ", v.end_is_block);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CGX_DRIVER_MESSAGE_ROBOTMOVECIRCLEREQUEST_H
